

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/biblioteca
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher